### ISSUE TITLE
setup.py fail on Ubuntu

### ISSUE THREAD

**Issue by Bhupesh-V** [sebcagnon/PyGoogleForm#3]
the command 
```bash
pip3 install PyGoogleForm 
```
is failing & the following error is returned 
```bash
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ntjku_ew/PyGoogleForm/setup.py", line 26
        except ImportError, IOError:
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ntjku_ew/PyGoogleForm/

```

**Comment by fruch** [comment]
Seems like this package needs some python3 love...

**Comment by Bhupesh-V** [comment]
Looks like it, IDK the maintainer is busy I guess

**Comment by fruch** [comment]
I've looked into it, and the python3 part isn't enough.
It's totally not up-to-date. and won't work even on python 2.7

I've found this in a better shape,
https://github.com/joeltio/google-form-python

Also that package need some love to be updated and tested with newer version of the forms
