### ISSUE TITLE
It doesn't install 😞

### ISSUE THREAD

**Issue by hhaider15** [sebcagnon/PyGoogleForm#5]
Hey there.

> pip install PyGoogleForm yields 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.'

**Comment by jaredliw** [comment]
Me too.  `git clone` also can't: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jared\Desktop\PyGoogleForm\__init__.py", line 1, in <module>
    from FormParser import *
ModuleNotFoundError: No module named 'FormParser'`
